Update terraform-cicd.yaml

diff --git a/.github/workflows/terraform-cicd.yaml b/.github/workflows/terraform-cicd.yaml
--- a/.github/workflows/terraform-cicd.yaml
+++ b/.github/workflows/terraform-cicd.yaml
@@ -1,61 +1,61 @@
-name: "Terraform Deploy S3 Static website"
-on:  
-  push:
-  pull_request:
-    branches:
-      - master
-jobs:
-  terraform:
-    name: "Terraform"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+# name: "Terraform Deploy S3 Static website"
+# on:  
+#   push:
+#   pull_request:
+#     branches:
+#       - master
+# jobs:
+#   terraform:
+#     name: "Terraform"
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          # terraform_version: 0.13.0:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}     
-      - name: Terraform Format
-        id: fmt
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform fmt -check
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           # terraform_version: 0.13.0:
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}     
+#       - name: Terraform Format
+#         id: fmt
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform init
+#       - name: Terraform Init
+#         id: init
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform init
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'push'
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform plan -no-color
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'push'
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform plan -no-color
+#         continue-on-error: true
 
-      - name: Stop on Terraform Plan Failure
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Stop on Terraform Plan Failure
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.event_name == 'push'
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform apply -auto-approve
-        continue-on-error: true
+#       - name: Terraform Apply
+#         if: github.event_name == 'push'
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform apply -auto-approve
+#         continue-on-error: true
 
-      - name: Configure AWS Credentials 
-        uses: aws-actions/configure-aws-credentials@v1 
-        with: 
-         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
-         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
-         aws-region: us-east-1
+#       - name: Configure AWS Credentials 
+#         uses: aws-actions/configure-aws-credentials@v1 
+#         with: 
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
+#          aws-region: us-east-1
 
-      - name: change directory & Deploy static site to S3 bucket 
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/public && aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}
+#       - name: change directory & Deploy static site to S3 bucket 
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/public && aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}
       
-      - name: sleep
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/scripts && sh break.sh
-        shell: bash
+#       - name: sleep
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/scripts && sh break.sh
+#         shell: bash
       
-      - name: change directory & Empty S3 bucket content
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/public && aws s3 rb s3://${{ secrets.S3_BUCKET_NAME }} --force  
+#       - name: change directory & Empty S3 bucket content
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/public && aws s3 rb s3://${{ secrets.S3_BUCKET_NAME }} --force  
       
-      - name: Destroy Infrastructure after creation
-        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform destroy -auto-approve
+#       - name: Destroy Infrastructure after creation
+#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/dev && terraform destroy -auto-approve
